# -*- coding: utf-8 -*-
"""
Firefly Rise — Site Data
All copy, service definitions, translations, FAQs, reviews, etc.
Consumed by build_site.py to generate 27 HTML pages.
"""

# ── Business identity ─────────────────────────────────────────────────────────
BUSINESS = {
    "name": "Firefly Rise",
    "industry_en": "Home Services Digital Marketing Agency",
    "industry_es": "Agencia de Marketing Digital para Servicios del Hogar",
    "phone": "602-829-0009",
    "phone_display": "(602) 829-0009",
    "phone_tel": "+16028290009",
    "email": "mgarcia4@gmail.com",
    "domain": "fireflyrise.com",
    "tagline_en": "Marketing built exclusively for home service contractors.",
    "tagline_es": "Marketing creado exclusivamente para contratistas de servicios del hogar.",
    "main_service_en": "Home Services Digital Marketing",
    "main_service_es": "Marketing Digital para Servicios del Hogar",
    "spanish_region": "es-US",
    "webhook_placeholder": "REPLACE_WITH_PABBLY_WEBHOOK_URL",
}

HOME_EN_PATH = "/"
HOME_EN_FILE = "index.html"
HOME_ES_FILE = "marketing-digital-para-servicios-del-hogar.html"
HOME_ES_PATH = "/" + HOME_ES_FILE

# ── Services ──────────────────────────────────────────────────────────────────
# Each service has rich content for its dedicated page.
SERVICES = [
    {
        "slug_en": "google-ads-management",
        "slug_es": "administracion-de-google-ads",
        "name_en": "Google Ads Management",
        "name_es": "Administración de Google Ads",
        "title_en": "Google Ads Management",
        "title_es": "Administración de Google Ads",
        "short_en": "PPC campaigns engineered for booked jobs — not vanity clicks.",
        "short_es": "Campañas PPC diseñadas para trabajos agendados — no clics vacíos.",
        "hero_headline_en": "Stop Burning Cash On Google Ads That Never Ring Your Phone",
        "hero_headline_es": "Deja De Quemar Dinero En Google Ads Que Nunca Hacen Sonar Tu Teléfono",
        "hero_body_en": "You don't need more clicks. You need more calls. Get Google Ads campaigns built by a team that only works with home service contractors — engineered for booked jobs, tracked down to the phone call, and transparent down to the last dollar.",
        "hero_body_es": "No necesitas más clics. Necesitas más llamadas. Campañas de Google Ads diseñadas por un equipo que solo trabaja con contratistas de servicios del hogar — enfocadas en trabajos agendados, rastreadas hasta la llamada, y transparentes hasta el último dólar.",
        "meta_desc_en": "Home services Google Ads management built for booked jobs, not clicks. Transparent reporting, no long-term contracts. Call (602) 829-0009.",
        "meta_desc_es": "Administración de Google Ads para servicios del hogar diseñada para agendar trabajos reales. Reportes transparentes, sin contratos largos. Llama al (602) 829-0009.",
        "card_title_en": "Google Ads That Actually Ring Your Phone",
        "card_title_es": "Google Ads Que Realmente Hacen Sonar Tu Teléfono",
        "card_text_en": "Hyper-targeted PPC campaigns built for plumbers, HVAC, roofers, and every other home service trade. Every ad, keyword, and landing page is engineered to put homeowners ready to book in front of you — today.",
        "card_text_es": "Campañas PPC hiper-segmentadas para plomeros, HVAC, techadores y toda clase de contratistas. Cada anuncio y página de aterrizaje está diseñada para poner frente a ti a dueños listos para agendar — hoy.",
        "pain_en": "You've spent thousands on Google Ads before — sometimes with other agencies, sometimes running them yourself — and all you have to show for it is an empty calendar and a bad taste in your mouth.",
        "pain_es": "Ya gastaste miles en Google Ads antes — a veces con otras agencias, a veces solo — y todo lo que tienes para mostrar es un calendario vacío y un mal sabor de boca.",
    },
    {
        "slug_en": "facebook-meta-ads",
        "slug_es": "anuncios-en-facebook-y-meta",
        "name_en": "Facebook & Meta Ads",
        "name_es": "Anuncios en Facebook y Meta",
        "title_en": "Facebook & Meta Ads",
        "title_es": "Anuncios en Facebook y Meta",
        "short_en": "Reach homeowners before they even think to Google your service.",
        "short_es": "Llega a los dueños de casa antes de que piensen en buscarte en Google.",
        "hero_headline_en": "Reach Homeowners Before They Even Google Your Service",
        "hero_headline_es": "Llega A Los Dueños De Casa Antes De Que Te Busquen En Google",
        "hero_body_en": "Facebook and Instagram aren't just for cat videos — they're where your next customers are scrolling right now. Put your business in front of homeowners who don't even know they need you yet, with ads that turn attention into phone calls.",
        "hero_body_es": "Facebook e Instagram no son solo para videos de gatos — es donde tus próximos clientes están ahora mismo. Pon tu negocio frente a dueños de casa que aún no saben que te necesitan, con anuncios que convierten atención en llamadas.",
        "meta_desc_en": "Facebook & Meta Ads built for home service contractors. Reach homeowners before they search. Call (602) 829-0009.",
        "meta_desc_es": "Anuncios en Facebook y Meta para contratistas de servicios del hogar. Llega a los dueños antes de que busquen. Llama al (602) 829-0009.",
        "card_title_en": "Capture Homeowners On Facebook & Instagram",
        "card_title_es": "Captura Dueños De Casa En Facebook E Instagram",
        "card_text_en": "Hyper-local Facebook and Instagram ads that put your business in front of homeowners right when they're most receptive. Get leads at a fraction of what Google clicks cost.",
        "card_text_es": "Anuncios locales en Facebook e Instagram que ponen tu negocio frente a dueños de casa justo cuando están más receptivos. Obtén leads a una fracción del costo de Google.",
        "pain_en": "You've tried boosting posts and running ads yourself — you got likes, comments, maybe a few cold DMs — but zero leads that turned into booked jobs.",
        "pain_es": "Ya intentaste promocionar publicaciones y correr anuncios por tu cuenta — obtuviste likes, comentarios, tal vez algunos mensajes — pero cero leads que se convirtieron en trabajos.",
    },
    {
        "slug_en": "website-design-development",
        "slug_es": "diseno-y-desarrollo-web",
        "name_en": "Website Design & Development",
        "name_es": "Diseño y Desarrollo Web",
        "title_en": "Website Design & Development",
        "title_es": "Diseño y Desarrollo Web",
        "short_en": "Websites built to convert visitors into booked jobs — not digital brochures.",
        "short_es": "Sitios web diseñados para convertir visitantes en trabajos agendados — no folletos digitales.",
        "hero_headline_en": "Your Website Should Be Your Best Salesperson — Not A Digital Brochure",
        "hero_headline_es": "Tu Sitio Web Debe Ser Tu Mejor Vendedor — No Un Folleto Digital",
        "hero_body_en": "Every day your website sits there looking pretty instead of generating leads, you're losing jobs to competitors with sites built for conversion. Get a website engineered from the ground up to turn visitors into phone calls.",
        "hero_body_es": "Cada día que tu sitio web solo se ve bonito sin generar leads, estás perdiendo trabajos con competidores. Obtén un sitio diseñado desde cero para convertir visitantes en llamadas telefónicas.",
        "meta_desc_en": "Home services website design built to convert visitors into booked jobs. Fast, mobile-first, SEO-ready. Call (602) 829-0009.",
        "meta_desc_es": "Diseño web para servicios del hogar que convierte visitantes en trabajos. Rápido, móvil, con SEO. Llama al (602) 829-0009.",
        "card_title_en": "A Website That Works As Hard As You Do",
        "card_title_es": "Un Sitio Web Que Trabaja Tan Duro Como Tú",
        "card_text_en": "Mobile-first, lightning-fast, SEO-ready websites purpose-built for home service contractors. Every page, headline, and button engineered to turn visitors into phone calls and booked jobs.",
        "card_text_es": "Sitios rápidos, móviles y listos para SEO, diseñados para contratistas. Cada página está hecha para convertir visitantes en llamadas y trabajos.",
        "pain_en": "Your current website was built by a cousin, a friend, or a template you bought in 2014 — and you're embarrassed to send prospects to it because you know it won't close anyone.",
        "pain_es": "Tu sitio actual lo hizo un primo, un amigo, o una plantilla que compraste en 2014 — y te da pena enviar prospectos porque sabes que no cerrará a nadie.",
    },
    {
        "slug_en": "landing-page-design",
        "slug_es": "diseno-de-paginas-de-aterrizaje",
        "name_en": "Landing Page Design",
        "name_es": "Diseño de Páginas de Aterrizaje",
        "title_en": "Landing Page Design",
        "title_es": "Diseño de Páginas de Aterrizaje",
        "short_en": "Dedicated pages that turn ad clicks into booked jobs at 2–5× the rate.",
        "short_es": "Páginas dedicadas que convierten clics en trabajos 2–5 veces más.",
        "hero_headline_en": "Turn Every Ad Click Into A Booked Job With Pages Built To Convert",
        "hero_headline_es": "Convierte Cada Clic De Anuncio En Un Trabajo Agendado",
        "hero_body_en": "The page your ads land on matters more than the ad itself. Stop sending expensive traffic to your homepage and watching it bounce — get landing pages engineered to convert ad visitors at 2 to 5 times the rate.",
        "hero_body_es": "La página donde aterrizan tus anuncios importa más que el anuncio mismo. Deja de enviar tráfico caro a tu página principal y verlo irse — obtén páginas diseñadas para convertir de 2 a 5 veces más.",
        "meta_desc_en": "High-converting landing pages for home services ads. 2–5× more leads from the same ad spend. Call (602) 829-0009.",
        "meta_desc_es": "Páginas de aterrizaje de alta conversión para servicios del hogar. 2–5× más leads con el mismo gasto. Llama al (602) 829-0009.",
        "card_title_en": "Pages That Turn Clicks Into Phone Calls",
        "card_title_es": "Páginas Que Convierten Clics En Llamadas",
        "card_text_en": "Purpose-built landing pages for every ad campaign — focused on one action, one outcome, and zero distractions. Convert more leads without spending another dollar on ads.",
        "card_text_es": "Páginas de aterrizaje hechas para cada campaña — una acción, un resultado, cero distracciones. Más leads sin gastar más en anuncios.",
        "pain_en": "You're running ads to your homepage and wondering why conversion is terrible — because your homepage is trying to serve everyone, which means it converts no one.",
        "pain_es": "Estás corriendo anuncios a tu página principal y te preguntas por qué la conversión es terrible — porque trata de servir a todos y termina convirtiendo a nadie.",
    },
    {
        "slug_en": "lead-generation",
        "slug_es": "generacion-de-prospectos",
        "name_en": "Lead Generation",
        "name_es": "Generación de Prospectos",
        "title_en": "Lead Generation",
        "title_es": "Generación de Prospectos",
        "short_en": "Exclusive, vetted homeowner leads sent directly to your phone.",
        "short_es": "Leads exclusivos y verificados enviados directo a tu teléfono.",
        "hero_headline_en": "Stop Competing For Shared Leads — Get Exclusive Homeowner Calls Sent Directly To You",
        "hero_headline_es": "Deja De Competir Por Leads Compartidos — Recibe Llamadas Exclusivas Directamente",
        "hero_body_en": "HomeAdvisor and Angi sell the same lead to five contractors and watch you fight over scraps. Get exclusive, vetted homeowner leads generated specifically for your service area — yours alone, never shared, never resold.",
        "hero_body_es": "HomeAdvisor y Angi venden el mismo lead a cinco contratistas y te hacen pelear por migajas. Obtén leads exclusivos y verificados generados solo para tu área — solo tuyos, nunca compartidos.",
        "meta_desc_en": "Exclusive home service lead generation. Never shared, never resold. Real homeowners ready to book. Call (602) 829-0009.",
        "meta_desc_es": "Generación de leads exclusivos para servicios del hogar. Nunca compartidos. Dueños listos para agendar. Llama al (602) 829-0009.",
        "card_title_en": "Exclusive Leads — Never Shared, Never Resold",
        "card_title_es": "Leads Exclusivos — Nunca Compartidos, Nunca Revendidos",
        "card_text_en": "Real homeowners, actively looking for your service, in your exact service area — delivered exclusively to you. No shared leads, no bidding wars, no stale contacts.",
        "card_text_es": "Dueños de casa reales, buscando tu servicio, en tu área de servicio exacta — entregados exclusivamente a ti. Sin leads compartidos, sin guerras de precios.",
        "pain_en": "You're tired of paying for shared leads from HomeAdvisor, Angi, or Thumbtack — sent to five other contractors at the same time — and most never even pick up the phone.",
        "pain_es": "Estás harto de pagar por leads compartidos de HomeAdvisor, Angi o Thumbtack — enviados a otros cinco contratistas — y la mayoría nunca contesta el teléfono.",
    },
    {
        "slug_en": "reputation-management",
        "slug_es": "manejo-de-reputacion",
        "name_en": "Reputation Management",
        "name_es": "Manejo de Reputación",
        "title_en": "Reputation Management",
        "title_es": "Manejo de Reputación",
        "short_en": "Build the 5-star reputation that makes homeowners choose you first.",
        "short_es": "Construye la reputación de 5 estrellas que hace que los dueños te elijan primero.",
        "hero_headline_en": "Build The 5-Star Reputation That Makes Homeowners Choose You First",
        "hero_headline_es": "Construye La Reputación De 5 Estrellas Que Te Convierte En La Primera Opción",
        "hero_body_en": "Homeowners read reviews before they ever pick up the phone. If your competitor has 200 five-star reviews and you have 12, you've already lost. Get a systematic review-generation machine that stacks the deck in your favor — fast.",
        "hero_body_es": "Los dueños de casa leen reseñas antes de levantar el teléfono. Si tu competidor tiene 200 reseñas de 5 estrellas y tú tienes 12, ya perdiste. Obtén una máquina sistemática de reseñas que inclina la balanza a tu favor — rápido.",
        "meta_desc_en": "Reputation management for home service contractors. Build 5-star reviews that close more jobs. Call (602) 829-0009.",
        "meta_desc_es": "Manejo de reputación para contratistas. Construye reseñas de 5 estrellas que cierran más trabajos. Llama al (602) 829-0009.",
        "card_title_en": "Turn Happy Customers Into A Wall Of 5-Star Reviews",
        "card_title_es": "Convierte Clientes Felices En Una Pared De Reseñas De 5 Estrellas",
        "card_text_en": "Automated review-generation that turns every happy customer into a 5-star review — on Google, Yelp, Facebook, BBB — while quietly managing unhappy ones before they ever go public.",
        "card_text_es": "Generación automática de reseñas que convierte a cada cliente feliz en una reseña de 5 estrellas — en Google, Yelp, Facebook, BBB — mientras maneja las quejas antes de que se hagan públicas.",
        "pain_en": "One bad review sitting at the top of your Google listing is costing you jobs every single day — and you don't know how to push it down or get more 5-stars in its place.",
        "pain_es": "Una mala reseña arriba en tu perfil de Google te está costando trabajos todos los días — y no sabes cómo empujarla abajo ni obtener más 5 estrellas.",
    },
    {
        "slug_en": "google-business-profile-optimization",
        "slug_es": "optimizacion-de-google-business-profile",
        "name_en": "Google Business Profile Optimization",
        "name_es": "Optimización de Google Business Profile",
        "title_en": "Google Business Profile Optimization",
        "title_es": "Optimización de Google Business Profile",
        "short_en": "Dominate the map pack in every city you serve.",
        "short_es": "Domina el map pack en cada ciudad que sirves.",
        "hero_headline_en": "Own The Google Map Pack — Show Up First When Homeowners Search",
        "hero_headline_es": "Domina El Map Pack De Google — Aparece Primero Cuando Los Dueños Buscan",
        "hero_body_en": "The top three spots on Google Maps capture 75% of all local clicks. If you're not in the 3-pack, you're invisible — no matter how good your service is. Get your Google Business Profile fully optimized to dominate the map pack in every city you serve.",
        "hero_body_es": "Los tres primeros lugares en Google Maps capturan el 75% de los clics locales. Si no estás en el 3-pack, eres invisible — sin importar qué tan bueno seas. Optimiza tu Google Business Profile para dominar el map pack en cada ciudad.",
        "meta_desc_en": "Google Business Profile optimization for home services. Rank in the map pack. More calls, more jobs. Call (602) 829-0009.",
        "meta_desc_es": "Optimización de Google Business Profile para servicios del hogar. Posiciona en el map pack. Más llamadas. Llama al (602) 829-0009.",
        "card_title_en": "Dominate Your Local Google Map Pack",
        "card_title_es": "Domina El Map Pack De Google Local",
        "card_text_en": "Full Google Business Profile optimization — categories, photos, posts, Q&A, review velocity, and GEO signals — so you rank #1 in the 3-pack in every city you serve.",
        "card_text_es": "Optimización completa de Google Business Profile — categorías, fotos, publicaciones, reseñas y señales GEO — para que aparezcas #1 en cada ciudad.",
        "pain_en": "You claimed your Google listing years ago and thought that was enough — but your competitors are ranking above you and you can't figure out why.",
        "pain_es": "Reclamaste tu perfil de Google hace años y pensaste que era suficiente — pero tus competidores están arriba de ti y no sabes por qué.",
    },
    {
        "slug_en": "conversion-rate-optimization",
        "slug_es": "optimizacion-de-conversiones",
        "name_en": "Conversion Rate Optimization",
        "name_es": "Optimización de Conversiones",
        "title_en": "Conversion Rate Optimization",
        "title_es": "Optimización de Conversiones",
        "short_en": "Double your leads without spending another dollar on ads.",
        "short_es": "Duplica tus leads sin gastar un dólar más en anuncios.",
        "hero_headline_en": "Double Your Leads Without Spending Another Dollar On Ads",
        "hero_headline_es": "Duplica Tus Leads Sin Gastar Un Dólar Más En Anuncios",
        "hero_body_en": "You don't need more traffic — you need more of your existing traffic to actually pick up the phone. Data-driven conversion rate optimization that turns your current visitors into leads, without adding a single dollar to your ad budget.",
        "hero_body_es": "No necesitas más tráfico — necesitas que tu tráfico actual levante el teléfono. Optimización de conversiones basada en datos que convierte a tus visitantes actuales en leads, sin aumentar tu presupuesto.",
        "meta_desc_en": "Conversion rate optimization for home service websites. Double leads with the same ad spend. Call (602) 829-0009.",
        "meta_desc_es": "Optimización de conversiones para sitios de servicios del hogar. Duplica tus leads. Llama al (602) 829-0009.",
        "card_title_en": "Get More Leads From The Traffic You Already Have",
        "card_title_es": "Obtén Más Leads Del Tráfico Que Ya Tienes",
        "card_text_en": "A/B testing, heatmap analysis, and behavioral data applied to every page of your site — so every visitor is more likely to become a booked job. More leads, same traffic.",
        "card_text_es": "Pruebas A/B, mapas de calor y datos de comportamiento aplicados a cada página — para que cada visitante sea más probable de convertir. Más leads, mismo tráfico.",
        "pain_en": "You're getting traffic — maybe even good traffic — but the phone still isn't ringing like it should, and you have no idea what's broken in your funnel.",
        "pain_es": "Estás recibiendo tráfico — tal vez buen tráfico — pero el teléfono no suena como debería, y no sabes qué está mal en tu embudo.",
    },
    {
        "slug_en": "call-tracking-analytics",
        "slug_es": "seguimiento-de-llamadas-y-analitica",
        "name_en": "Call Tracking & Analytics",
        "name_es": "Seguimiento de Llamadas y Analítica",
        "title_en": "Call Tracking & Analytics",
        "title_es": "Seguimiento de Llamadas y Analítica",
        "short_en": "Know exactly which ads, keywords, and pages drive every phone call.",
        "short_es": "Conoce exactamente qué anuncios y páginas generan cada llamada.",
        "hero_headline_en": "Stop Guessing Which Ads Work — Know Exactly Where Every Call Comes From",
        "hero_headline_es": "Deja De Adivinar Qué Anuncios Funcionan — Conoce De Dónde Viene Cada Llamada",
        "hero_body_en": "You can't improve what you can't measure. Get granular call tracking that tells you exactly which ad, keyword, and page drove every incoming call — so you can kill what's wasting money and scale what's actually working.",
        "hero_body_es": "No puedes mejorar lo que no puedes medir. Obtén seguimiento de llamadas detallado que te dice exactamente qué anuncio, palabra clave y página generó cada llamada — para matar lo que desperdicia dinero y escalar lo que funciona.",
        "meta_desc_en": "Call tracking and analytics for home service contractors. Know which ads drive calls. Call (602) 829-0009.",
        "meta_desc_es": "Seguimiento de llamadas y analítica para contratistas. Sabe qué anuncios generan llamadas. Llama al (602) 829-0009.",
        "card_title_en": "Know Exactly Where Every Phone Call Comes From",
        "card_title_es": "Conoce De Dónde Viene Cada Llamada",
        "card_text_en": "Dynamic number insertion, keyword-level attribution, and full call recording — so you can see which ad, which keyword, and which page generated every phone call in your business.",
        "card_text_es": "Inserción dinámica de números, atribución por palabra clave y grabación de llamadas — para ver qué anuncio y qué página generó cada llamada.",
        "pain_en": "You're spending money on marketing and hoping it works — with no real way to tell which ads, keywords, or channels are actually driving calls versus burning money.",
        "pain_es": "Estás gastando en marketing y esperando que funcione — sin saber qué anuncios o canales están generando llamadas versus quemando dinero.",
    },
    {
        "slug_en": "branding-logo-design",
        "slug_es": "diseno-de-marca-y-logotipo",
        "name_en": "Branding & Logo Design",
        "name_es": "Diseño de Marca y Logotipo",
        "title_en": "Branding & Logo Design",
        "title_es": "Diseño de Marca y Logotipo",
        "short_en": "Look like the most trusted contractor in town — before you say a word.",
        "short_es": "Luce como el contratista más confiable — antes de decir una palabra.",
        "hero_headline_en": "Look Like The Most Trusted Contractor In Town — Before You Say A Word",
        "hero_headline_es": "Luce Como El Contratista Más Confiable — Antes De Decir Una Palabra",
        "hero_body_en": "Homeowners make up their minds about you in the first three seconds — before you ever shake their hand. Get a professional brand identity that communicates trust, quality, and expertise across every truck, uniform, business card, and website.",
        "hero_body_es": "Los dueños de casa deciden sobre ti en los primeros tres segundos — antes de darte la mano. Obtén una identidad de marca profesional que transmite confianza, calidad y experiencia en cada camión, uniforme y tarjeta.",
        "meta_desc_en": "Branding and logo design for home service contractors. Look professional, build trust, win more jobs. Call (602) 829-0009.",
        "meta_desc_es": "Diseño de marca y logotipo para contratistas. Luce profesional, genera confianza, gana más. Llama al (602) 829-0009.",
        "card_title_en": "A Brand That Homeowners Instantly Trust",
        "card_title_es": "Una Marca En La Que Los Dueños Confían Al Instante",
        "card_text_en": "Cohesive brand identity — logo, colors, truck wraps, uniforms, business cards, website — designed to build trust with homeowners the instant they see you.",
        "card_text_es": "Identidad de marca cohesiva — logotipo, colores, rotulación, uniformes, tarjetas y sitio web — diseñada para generar confianza al instante.",
        "pain_en": "Your current branding is a Canva logo slapped on a magnetic truck sign — and you're losing jobs to competitors who just look more professional than you do.",
        "pain_es": "Tu marca actual es un logo de Canva en un letrero magnético — y estás perdiendo trabajos con competidores que simplemente lucen más profesionales.",
    },
]

SERVICE_BY_SLUG_EN = {s["slug_en"]: s for s in SERVICES}
SERVICE_BY_SLUG_ES = {s["slug_es"]: s for s in SERVICES}

# ── FA icons per service (used in Why-Us / Steps across pages) ────────────────
# We reuse icons — validated FA7 Free Solid names.
WHY_US_ICONS = ["fa-solid fa-bullseye", "fa-solid fa-chart-line", "fa-solid fa-handshake"]
STEP_ICONS = ["fa-solid fa-phone", "fa-solid fa-clipboard-list", "fa-solid fa-circle-check"]

# ── Reviews (10 unique, spread across pages; homepage gets top 3) ────────────
REVIEWS_EN = [
    {
        "title": "They Finally Got My Phone Ringing Again",
        "body": "I'd burned almost $9,000 on Google Ads with another agency and got maybe 3 calls in 4 months. Firefly rebuilt my campaigns from scratch in week one. By week three my phone was ringing with real jobs — not tire kickers.",
        "name": "Marcus Reed, Houston, TX",
        "service": "google-ads-management",
    },
    {
        "title": "Facebook Ads Actually Work — Who Knew",
        "body": "I was convinced Facebook was a waste for HVAC. Firefly proved me dead wrong in 6 weeks. We're now booking 20+ installs a month off Facebook alone, at half the cost per lead of Google.",
        "name": "Aaron Whitaker, Tampa, FL",
        "service": "facebook-meta-ads",
    },
    {
        "title": "My New Site Closes Jobs While I'm Asleep",
        "body": "My old site was embarrassing — I'd literally skip mentioning it to prospects. The new one Firefly built is night and day. People call from it every single day now, and they've already decided they want me before the phone rings.",
        "name": "Lorenzo Silva, Denver, CO",
        "service": "website-design-development",
    },
    {
        "title": "Three Times The Leads From The Same Ad Budget",
        "body": "Same ads, same spend — but Firefly built me dedicated landing pages for each campaign. My lead volume more than tripled in the first month. I should have done this two years ago.",
        "name": "Danielle Foster, Charlotte, NC",
        "service": "landing-page-design",
    },
    {
        "title": "Finally, Leads I Don't Have To Fight Over",
        "body": "I gave up on HomeAdvisor after years of chasing shared leads. Firefly's exclusive leads are homeowners who only talked to me. My close rate jumped from 8% to almost 40%. Night and day.",
        "name": "Trevor Hanson, Columbus, OH",
        "service": "lead-generation",
    },
    {
        "title": "From 14 Reviews To 180 In One Year",
        "body": "I had 14 Google reviews when I started with Firefly. A year later I'm at 180 and climbing — and I didn't lift a finger. Every single new customer now mentions my reviews on the first call.",
        "name": "Janelle Ortiz, Phoenix, AZ",
        "service": "reputation-management",
    },
    {
        "title": "I Finally Show Up On Google Maps",
        "body": "I used to be invisible in the 3-pack no matter what city I searched. After Firefly optimized my Google Business Profile, I'm ranking #1 in six of my eight service areas. The calls speak for themselves.",
        "name": "Richard Beasley, Raleigh, NC",
        "service": "google-business-profile-optimization",
    },
    {
        "title": "Doubled My Leads, Zero Extra Ad Spend",
        "body": "Firefly didn't tell me to spend more — they fixed what was already broken. Same traffic, same budget, double the leads. The ROI on this was immediate and it's still paying off six months later.",
        "name": "Priya Sharma, Austin, TX",
        "service": "conversion-rate-optimization",
    },
    {
        "title": "I Finally Know Which Ads Actually Work",
        "body": "For years I had no idea where my calls came from — I was just guessing. Firefly set up call tracking and within 30 days I killed two ad groups that were burning cash and doubled budget on what was working. Immediate profit.",
        "name": "Ethan Morales, Nashville, TN",
        "service": "call-tracking-analytics",
    },
    {
        "title": "Homeowners Trust Me Before I Say Hello",
        "body": "My truck, uniforms, and site all look totally different now — and I can see it in how customers treat me the second I pull up. Jobs close faster and at higher prices because I look like I belong at the top.",
        "name": "Nikki Palmer, Kansas City, MO",
        "service": "branding-logo-design",
    },
]

REVIEWS_ES = [
    {
        "title": "Por Fin Suena Mi Teléfono De Nuevo",
        "body": "Había quemado casi $9,000 en Google Ads con otra agencia y recibí tal vez 3 llamadas en 4 meses. Firefly reconstruyó mis campañas desde cero en la primera semana. Para la semana tres mi teléfono sonaba con trabajos reales — no curiosos.",
        "name": "Marcus Reed, Houston, TX",
        "service": "administracion-de-google-ads",
    },
    {
        "title": "Facebook Ads Sí Funcionan — Quién Lo Diría",
        "body": "Estaba convencido de que Facebook era pérdida de tiempo para HVAC. Firefly me demostró lo contrario en 6 semanas. Ahora agendamos 20+ instalaciones al mes solo con Facebook, a la mitad del costo por lead que en Google.",
        "name": "Aaron Whitaker, Tampa, FL",
        "service": "anuncios-en-facebook-y-meta",
    },
    {
        "title": "Mi Nuevo Sitio Cierra Trabajos Mientras Duermo",
        "body": "Mi sitio anterior era vergonzoso — ni lo mencionaba a mis prospectos. El nuevo que hizo Firefly es día y noche. La gente llama desde él todos los días, y ya decidieron que me quieren antes de que suene el teléfono.",
        "name": "Lorenzo Silva, Denver, CO",
        "service": "diseno-y-desarrollo-web",
    },
    {
        "title": "Tres Veces Más Leads Con El Mismo Presupuesto",
        "body": "Mismos anuncios, mismo gasto — pero Firefly me hizo páginas de aterrizaje dedicadas para cada campaña. Mis leads se triplicaron el primer mes. Debí haber hecho esto hace dos años.",
        "name": "Danielle Foster, Charlotte, NC",
        "service": "diseno-de-paginas-de-aterrizaje",
    },
    {
        "title": "Por Fin, Leads Por Los Que No Tengo Que Pelear",
        "body": "Me rendí con HomeAdvisor después de años persiguiendo leads compartidos. Los leads exclusivos de Firefly son dueños que solo hablaron conmigo. Mi tasa de cierre saltó del 8% a casi 40%. Día y noche.",
        "name": "Trevor Hanson, Columbus, OH",
        "service": "generacion-de-prospectos",
    },
    {
        "title": "De 14 Reseñas A 180 En Un Año",
        "body": "Tenía 14 reseñas en Google cuando empecé con Firefly. Un año después tengo 180 y subiendo — y no moví un dedo. Cada cliente nuevo ahora menciona mis reseñas en la primera llamada.",
        "name": "Janelle Ortiz, Phoenix, AZ",
        "service": "manejo-de-reputacion",
    },
    {
        "title": "Por Fin Aparezco En Google Maps",
        "body": "Era invisible en el 3-pack sin importar qué ciudad buscara. Después de que Firefly optimizó mi perfil, aparezco #1 en seis de mis ocho áreas de servicio. Las llamadas hablan por sí solas.",
        "name": "Richard Beasley, Raleigh, NC",
        "service": "optimizacion-de-google-business-profile",
    },
    {
        "title": "Dupliqué Mis Leads, Cero Gasto Extra",
        "body": "Firefly no me dijo que gastara más — arregló lo que ya estaba roto. Mismo tráfico, mismo presupuesto, el doble de leads. El ROI fue inmediato y sigue pagando seis meses después.",
        "name": "Priya Sharma, Austin, TX",
        "service": "optimizacion-de-conversiones",
    },
    {
        "title": "Por Fin Sé Qué Anuncios Funcionan",
        "body": "Por años no sabía de dónde venían mis llamadas — solo adivinaba. Firefly configuró seguimiento y en 30 días maté dos grupos de anuncios que quemaban dinero y dupliqué presupuesto en los que funcionaban. Ganancia inmediata.",
        "name": "Ethan Morales, Nashville, TN",
        "service": "seguimiento-de-llamadas-y-analitica",
    },
    {
        "title": "Los Dueños Confían Antes De Saludarlos",
        "body": "Mi camión, uniformes y sitio lucen totalmente diferentes — y se nota en cómo me tratan los clientes. Los trabajos se cierran más rápido y a precios más altos porque luzco como que pertenezco ahí arriba.",
        "name": "Nikki Palmer, Kansas City, MO",
        "service": "diseno-de-marca-y-logotipo",
    },
]
